---
title: "Using Covidestim"
author: "Melanie H. Chitwood, Marcus Russi" 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using Covidestim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
**This vignette is intended to guide users through running the covidestim model and 
accessing the model output.**




```r
library(covidestim)
```

## Running the model 
### Data
Will we demonstrate how to use the covidestim paackage using data from the [Massachusetts Department of Public Health](https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts) 
Users can use case and/or death data with the model. Data on the fraction of tests with a positive results may also be used; we strongly recommend users smooth fraciton positive data using a moving average or spline. Each data type should be entered as its own dataframe with two columns: a column called 'date' and a column called 'observation.' 



```r
head(df.cases)
#> # A tibble: 6 x 2
#>   date       observation
#>   <date>           <dbl>
#> 1 2020-03-01           1
#> 2 2020-03-02           0
#> 3 2020-03-03           1
#> 4 2020-03-04           2
#> 5 2020-03-05           8
#> 6 2020-03-06          14
```
### Generate a model configuration 
Inpute data and model run options are summarized into a covidestim configuration with the funciton call [`covidestim()`](\code{?covidestim}). Users must specify the number of days of data in the input data. More information on data formating can be found [here](\code{?input_cases}). Calling `covidestim()` will produce a summary of model run conditions, priors, and data inputs. 

```r
covidestim(ndays = nrow(df.cases)) 
#> Covidestim Configuration:
#> 
#> Seed:	42
#> Chains:	3
#> Iterations:	1500
#> Warmup runs:	1200
#> Priors: Valid
#> ndays:	103
#> 
#> Priors:
#> 
#> 	log_new_inf_0_mu	0
#> 	log_new_inf_0_sd	10
#> 	deriv1_log_new_inf_sd	0.5
#> 	deriv2_log_new_inf_sd	0.05
#> 	p_sym_if_inf	[alpha]	44.9
#> 	p_sym_if_inf	[beta]	9.9
#> 	p_sev_if_sym	[alpha]	11.9
#> 	p_sev_if_sym	[beta]	47.7
#> 	p_die_if_sev	[alpha]	3
#> 	p_die_if_sev	[beta]	97
#> 	p_die_if_sym	[alpha]	1.12
#> 	p_die_if_sym	[beta]	85.1
#> 	inf_prg_delay	[shape]	5.202
#> 	inf_prg_delay	[rate]	0.946
#> 	sym_prg_delay	[shape]	5.147
#> 	sym_prg_delay	[rate]	0.468
#> 	sev_prg_delay	[shape]	2.383
#> 	sev_prg_delay	[rate]	0.27
#> 	cas_rep_delay_shp	[alpha]	2.2
#> 	cas_rep_delay_shp	[beta]	1
#> 	die_rep_delay_shp	[alpha]	2.2
#> 	die_rep_delay_shp	[beta]	1
#> 	p_diag_if_sym	[alpha]	2
#> 	p_diag_if_sym	[beta]	2
#> 	p_diag_if_sev	[alpha]	1.5
#> 	p_diag_if_sev	[beta]	1
#> 	weekend_eff	[alpha]	2
#> 	weekend_eff	[beta]	2
#> 
#> Inputs:
#> 
#> 	[ ❌ ]	Cases
#> 	[ ❌ ]	Deaths
#> 	[ ❌ ]	Fraction positive
```
Notice that what we input is **not** a valid model configuration because it does not contain data! Each dataframe must be added to the covidestim call using calls [`input_cases()`](\code{?input_cases}),  [`input_deaths()`](\code{?input_deaths}), and [`input_fracpos()`](\code{?input_fracpos}). Whether the data are by date-of-occurrence (e.g date of test specimen collection, date of death) or by date-of-report (e.g. daily updates to cumulative case and death counts) must be noted.   
  
Because we use date-of-occurrence data, we choose to enable the 'weekend effect.' As individuals are less likely to be tested on Saturdays and Sundays, enabling the weekend effect allows the model to estimate a systematically lower probability of diagnosis on the weekend. This generally improves model fit to data when the data are by date-of-occurrence. 
For additional information about changing the base configuration of the model, see [`covidestim()`](\code{?covidestim}). 

```r
config1 <-
covidestim(ndays = nrow(df.cases), weekend = TRUE) +
  input_cases(df.cases, type = "occurred") + 
  input_deaths(df.cases, type = "occurred") + 
  input_fracpos(df.fracpos)
config1
#> Covidestim Configuration:
#> 
#> Seed:	42
#> Chains:	3
#> Iterations:	1500
#> Warmup runs:	1200
#> Priors: Valid
#> ndays:	103
#> 
#> Priors:
#> 
#> 	log_new_inf_0_mu	0
#> 	log_new_inf_0_sd	10
#> 	deriv1_log_new_inf_sd	0.5
#> 	deriv2_log_new_inf_sd	0.05
#> 	p_sym_if_inf	[alpha]	44.9
#> 	p_sym_if_inf	[beta]	9.9
#> 	p_sev_if_sym	[alpha]	11.9
#> 	p_sev_if_sym	[beta]	47.7
#> 	p_die_if_sev	[alpha]	3
#> 	p_die_if_sev	[beta]	97
#> 	p_die_if_sym	[alpha]	1.12
#> 	p_die_if_sym	[beta]	85.1
#> 	inf_prg_delay	[shape]	5.202
#> 	inf_prg_delay	[rate]	0.946
#> 	sym_prg_delay	[shape]	5.147
#> 	sym_prg_delay	[rate]	0.468
#> 	sev_prg_delay	[shape]	2.383
#> 	sev_prg_delay	[rate]	0.27
#> 	cas_rep_delay_shp	[alpha]	2.2
#> 	cas_rep_delay_shp	[beta]	1
#> 	die_rep_delay_shp	[alpha]	2.2
#> 	die_rep_delay_shp	[beta]	1
#> 	p_diag_if_sym	[alpha]	2
#> 	p_diag_if_sym	[beta]	2
#> 	p_diag_if_sev	[alpha]	1.5
#> 	p_diag_if_sev	[beta]	1
#> 	weekend_eff	[alpha]	2
#> 	weekend_eff	[beta]	2
#> 
#> Inputs:
#> 
#> 	[ 103]	Cases
#> 	[ 103]	Deaths
#> 	[ 103]	Fraction positive
```
### Initializing a model run
Finally, the model is run with the call [`run`](\code{?run}). Do not forget to assign the a name to the output of the run. Runtimes vary depending on the size and quality of the data, and may take over an hour. If you are running the model in RStudio, periodic status updates will appear in the console. 

```r
output <- run(config1, cores = parallel::detectCores())
```

## Accessing model output 
Calling `run()` on a valid covidestim configuration will produce a S3 object of class `covidestim_result` containing the configuration used to run the model ("config"), the raw results ("result"), the extracted result as produced by [`rstan::extract()`](https://mc-stan.org/rstan/reference/stanfit-method-extract.html) ("extracted"), and the summarized results as produced by [`rstan::summary`](https://mc-stan.org/rstan/reference/stanfit-method-summary.html) ("summary"). 




First, we describe summary functions in covidestim to view model results. Next, we describe the various items within `covidestim_result`.  

### Summarizing covidestim output
A covidestim object can be easily converted to a summary data frame with the call [`summary`](\code{?summary}). Each row of the data frame is a date. Each column of the data frame is a value of interest. Variables appened with .hi or .lo indicate the 0.975 and 0.025 quantiles, respectively. A data dictionary for summarized results can be found [here](\code{?summary}). 


```r
output.summary <- summary(output)
```

```r
head(output.summary)
#> # A tibble: 6 x 35
#>   date       cases.fitted cases.fitted.hi cases.fitted.lo cum.incidence
#>   <date>            <dbl>           <dbl>           <dbl>         <dbl>
#> 1 2020-02-02    0.0000160        0.000554     0.000000204         0.846
#> 2 2020-02-03    0.000329         0.0100       0.00000530          1.78 
#> 3 2020-02-04    0.00209          0.0503       0.0000431           2.80 
#> 4 2020-02-05    0.00678          0.128        0.000185            3.97 
#> 5 2020-02-06    0.0147           0.224        0.000437            5.23 
#> 6 2020-02-07    0.0248           0.348        0.000897            6.63 
#> # … with 30 more variables: deaths <dbl>, deaths.diagnosed <dbl>,
#> #   deaths.diagnosed.hi <dbl>, deaths.diagnosed.lo <dbl>,
#> #   deaths.fitted <dbl>, deaths.fitted.hi <dbl>,
#> #   deaths.fitted.lo <dbl>, deaths.hi <dbl>, deaths.lo <dbl>,
#> #   diagnoses <dbl>, diagnoses.hi <dbl>, diagnoses.lo <dbl>,
#> #   infections <dbl>, infections.hi <dbl>, infections.lo <dbl>,
#> #   severe <dbl>, severe.hi <dbl>, severe.lo <dbl>, symptomatic <dbl>,
#> #   symptomatic.hi <dbl>, symptomatic.lo <dbl>, data.available <lgl>,
#> #   Rt <dbl>, Rt.lo <I<dbl>>, Rt.hi <I<dbl>>, NaiveRt <dbl>,
#> #   NaiveRt.lo <dbl>, NaiveRt.hi <dbl>, cum.incidence.lo <dbl>,
#> #   cum.incidence.hi <dbl>
```

The posterior distributions of key time-invariant parameters can also be summarized with the call [`summaryEpi`](\?code{?summaryEpi})


```r
covidestim::summaryEpi(output)
#> # A tibble: 6 x 4
#>   par           `2.5%`  `50%` `97.5%`
#>   <chr>          <dbl>  <dbl>   <dbl>
#> 1 p_sym_if_inf  0.710  0.822   0.908 
#> 2 p_sev_if_sym  0.123  0.213   0.326 
#> 3 p_die_if_sev  0.0735 0.0859  0.104 
#> 4 p_die_if_sym  0.0104 0.0185  0.0269
#> 5 p_diag_if_sym 0.0296 0.0812  0.179 
#> 6 p_diag_if_sev 0.312  0.806   0.994
```
Note that p_diag_if_sym (the probability a symptomatic case is diagnosed) and p_diag_if_sev (the probability that a severe case is diagnosed) are summarized without the adjustment for changing diagnostic coverage. 

### result
Covidestim uses Bayesian inference to estiamte incident cases. The model is run using [rstan](https://mc-stan.org/users/interfaces/rstan), a package for the R programming language that allows for the estimation and analysis of Bayesian models with Stan. `result` is a stanfit object, the output of calling [`rstan::stan()`](https://mc-stan.org/rstan/reference/stanfit-class.html). 

We make use of the rstan functions [`summary()`](https://mc-stan.org/rstan/reference/stanfit-method-summary.html) and  [`extract()`](https://mc-stan.org/rstan/reference/stanfit-method-extract.html) to pull model results of interest for easy visualization and analysis. 

### extracted
`extracted` contains the point estimate for every parameter value in every iteration after warm-up. It is a named list, where every element is an array of samples from the paremeter. All three chains have been mixed. 


```r
summary(output[["extracted"]])
#>                      Length Class  Mode   
#> log_new_inf_0           900 -none- numeric
#> deriv1_log_new_inf   117000 -none- numeric
#> p_sym_if_inf            900 -none- numeric
#> p_sev_if_sym            900 -none- numeric
#> p_die_if_sev            900 -none- numeric
#> scale_dx_delay_sym      900 -none- numeric
#> scale_dx_delay_sev      900 -none- numeric
#> cas_rep_delay_shap      900 -none- numeric
#> cas_rep_delay_rate      900 -none- numeric
#> die_rep_delay_shap      900 -none- numeric
#> die_rep_delay_rate      900 -none- numeric
#> p_diag_if_sym           900 -none- numeric
#> p_diag_if_sev           900 -none- numeric
#> weekend_eff             900 -none- numeric
#> inv_sqrt_phi_c          900 -none- numeric
#> inv_sqrt_phi_d          900 -none- numeric
#> log_new_inf          117900 -none- numeric
#> new_inf              117900 -none- numeric
#> deriv2_log_new_inf   116100 -none- numeric
#> inf_prg_delay         54000 -none- numeric
#> sym_prg_delay         54000 -none- numeric
#> sev_prg_delay         54000 -none- numeric
#> sym_diag_delay        54000 -none- numeric
#> sev_diag_delay        54000 -none- numeric
#> cas_rep_delay         54000 -none- numeric
#> die_rep_delay         54000 -none- numeric
#> cas_cum_report_delay  54000 -none- numeric
#> die_cum_report_delay  54000 -none- numeric
#> p_die_if_sym            900 -none- numeric
#> new_sym              117900 -none- numeric
#> new_sev              117900 -none- numeric
#> new_die              117900 -none- numeric
#> new_sym_dx           117900 -none- numeric
#> dx_sym_sev           117900 -none- numeric
#> dx_sym_die           117900 -none- numeric
#> new_sev_dx           117900 -none- numeric
#> dx_sev_die           117900 -none- numeric
#> new_die_dx           117900 -none- numeric
#> diag_all             117900 -none- numeric
#> occur_cas            117900 -none- numeric
#> occur_die            117900 -none- numeric
#> phi_cas                 900 -none- numeric
#> phi_die                 900 -none- numeric
#> cumulative_incidence 117900 -none- numeric
#> lp__                    900 -none- numeric
```
In this format, it's possible to view the time series of estimates within a single iteration. 

```r
# a matrix of new infection point estimates for each timepoint, iteration
new_sym <- output[["extracted"]]$new_sym
# view first 8 iterations, first 5 days
new_sym[1:8, 1:5]
#>           
#> iterations         [,1]         [,2]        [,3]        [,4]
#>       [1,] 3.274829e-03 0.0560706616 0.219644176 0.477916283
#>       [2,] 5.032763e-05 0.0008716628 0.003556969 0.008219075
#>       [3,] 1.958447e-03 0.0335117160 0.130883960 0.282419126
#>       [4,] 1.570663e-03 0.0270281841 0.107926993 0.243060987
#>       [5,] 5.757425e-05 0.0009934615 0.003999409 0.009035890
#>       [6,] 1.460804e-03 0.0252677683 0.102576842 0.234446367
#>       [7,] 1.545208e-03 0.0265116400 0.104644103 0.230502169
#>       [8,] 3.610453e-03 0.0622773026 0.250509470 0.566421047
#>           
#> iterations       [,5]
#>       [1,] 0.76287176
#>       [2,] 0.01428653
#>       [3,] 0.44659259
#>       [4,] 0.40893295
#>       [5,] 0.01517172
#>       [6,] 0.40018058
#>       [7,] 0.37628729
#>       [8,] 0.95003396
```
This functionality is particularly useful for calculating an average with quantile-based bounds across multiple days of data. For example, we can calculate the average number of new infections over the first week of data. 

```r
# create a data frame with the final 7 days from the model 
new_sym_df <- as.data.frame(new_sym[,29:35]) 
# compute the row average 
new_sym_df$avg <- rowSums(new_sym_df)/7
# calculate the mean and 95% uncertainty bounds
quantile(new_sym_df$avg, probs = c(0.025,  0.5, 0.975))
#>      2.5%       50%     97.5% 
#>  54.62054 106.99165 298.04064
```
`extracted` is generally useful for cases where it's necessary to compute an average across multiple timepoints or when a user would like to represent uncertainty with non-quantile-based intervals (e.g. highest density intervals). 

### summary
`summary` contains the point estimate and uncertainty bounds for every parameter in the model. The number in brackets indicates the inex day of the estimate. `summary` also contains information about model fit, including the effective sample size and Rhat estimates. 

```r
head(output[["summary"]])
#>                              mean     se_mean        sd       2.5%
#> log_new_inf_0         -0.20513781 0.096584159 1.7019611 -3.7129190
#> deriv1_log_new_inf[1]  0.09328947 0.007057905 0.1490608 -0.1941232
#> deriv1_log_new_inf[2]  0.09288524 0.006673217 0.1410403 -0.1863570
#> deriv1_log_new_inf[3]  0.09333115 0.006440995 0.1310062 -0.1613550
#> deriv1_log_new_inf[4]  0.09454527 0.006044516 0.1247673 -0.1445126
#> deriv1_log_new_inf[5]  0.09915530 0.005979370 0.1206710 -0.1217462
#>                                25%         50%       75%     97.5%
#> log_new_inf_0         -1.273065857 -0.16726647 1.0535618 2.7781061
#> deriv1_log_new_inf[1] -0.012128721  0.09428490 0.1985366 0.3724622
#> deriv1_log_new_inf[2] -0.008922209  0.09393375 0.1923225 0.3679413
#> deriv1_log_new_inf[3]  0.005446738  0.09212803 0.1819946 0.3393304
#> deriv1_log_new_inf[4]  0.006003373  0.09236378 0.1808786 0.3380771
#> deriv1_log_new_inf[5]  0.008539548  0.09831075 0.1869341 0.3287108
#>                          n_eff     Rhat
#> log_new_inf_0         310.5185 1.007401
#> deriv1_log_new_inf[1] 446.0418 1.002887
#> deriv1_log_new_inf[2] 446.6999 1.003825
#> deriv1_log_new_inf[3] 413.6924 1.003046
#> deriv1_log_new_inf[4] 426.0676 1.005748
#> deriv1_log_new_inf[5] 407.2815 1.005308
```
While `summary` can be easily converted to a dataframe, we recommend using helper functions with covidestim. 


