---
title: "Results Object"
author: "Melanie H. Chitwood, Marcus Russi, Fayette Klaassen" 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results Object}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Covidestim Results

This guide is intended to describe the various result objects contained in the object produced by the call `covidestim::run()`. Note that most model timeseries estimates are readily available through calling `summary()` on a `covidestim_result` object. This guide explores the internals of the `covidestim_run` object, to aid the interested user in accessing timeseries outcomes from individual iterations of the NUTS sampler.

### Overview
Calling `run()` on a valid covidestim configuration will produce a S3 object of class `covidestim_result` containing the configuration used to run the model ("config"), the raw results ("result"), the extracted result as produced by [`rstan::extract()`](https://mc-stan.org/rstan/reference/stanfit-method-extract.html) ("extracted"), and the summarized results as produced by [`rstan::summary`](https://mc-stan.org/rstan/reference/stanfit-method-summary.html) ("summary"). 

### Result
Covidestim uses Bayesian inference to estimate incident cases. The model is run using [rstan](https://mc-stan.org/users/interfaces/rstan), a package for the R programming language that allows for the estimation and analysis of Bayesian models with Stan. `result` is a stanfit object, the output of calling [`rstan::stan()`](https://mc-stan.org/rstan/reference/stanfit-class.html). 

We make use of the rstan functions [`summary()`](https://mc-stan.org/rstan/reference/stanfit-method-summary.html) and  [`extract()`](https://mc-stan.org/rstan/reference/stanfit-method-extract.html) to pull model results of interest for easy visualization and analysis. 

### Extracted
`extracted` contains the point estimate for every parameter value in every iteration after warm-up. It is a named list, where every element is an array of samples from the parameter. All three chains have been mixed. 

```r
summary(resultSampler[["extracted"]])
```

```
##                                        Length Class  Mode   
## log_infections_0                          2001 -none- numeric
## serial_i                                  2001 -none- numeric
## spl_par_rt                               70035 -none- numeric
## p_sym_if_inf                              2001 -none- numeric
## new_p_sym_if_inf                          2001 -none- numeric
## p_sev_if_sym                              2001 -none- numeric
## p_die_if_sev                              2001 -none- numeric
## ifr_decl_OR                               2001 -none- numeric
## scale_dx_delay_sym                        2001 -none- numeric
## scale_dx_delay_sev                        2001 -none- numeric
## rr_diag_asy_vs_sym                        2001 -none- numeric
## p_diag_if_sev                             2001 -none- numeric
## spl_par_sym_dx                           24012 -none- numeric
## inv_sqrt_phi_c                            2001 -none- numeric
## inv_sqrt_phi_h                            2001 -none- numeric
## prob_vac                                  6003 -none- numeric
## log_infections                           70035 -none- numeric
## deriv1_log_infections                    70035 -none- numeric
## infections                               70035 -none- numeric
## ever_inf                                  2001 -none- numeric
## susceptible_prvl                         70035 -none- numeric
## population_protection_init               70035 -none- numeric
## population_protection_inf                70035 -none- numeric
## population_protection_boost              70035 -none- numeric
## effective_protection_prvl                70035 -none- numeric
## logRt0                                   70035 -none- numeric
## logRt                                    70035 -none- numeric
## r_t                                      70035 -none- numeric
## deriv1_spl_par_rt                        68034 -none- numeric
## deriv2_spl_par_rt                        66033 -none- numeric
## p_die_if_sevt                           122061 -none- numeric
## p_sev_if_symt                            70035 -none- numeric
## p_sym_if_inft                            70035 -none- numeric
## rr_diag_sym_vs_sev                       70035 -none- numeric
## p_diag_if_asy                            70035 -none- numeric
## p_diag_if_sym                            70035 -none- numeric
## sym_diag_delay_rv                        10005 -none- numeric
## sev_diag_delay_rv                        10005 -none- numeric
## p_die_if_inf                              2001 -none- numeric
## symptomatic                              70035 -none- numeric
## severe                                   70035 -none- numeric
## deaths                                   70035 -none- numeric
## new_asy_dx                               70035 -none- numeric
## diagnoses_of_symptomatic                 70035 -none- numeric
## diagnoses_severe                         70035 -none- numeric
## dx_sym_sev                               70035 -none- numeric
## dx_sym_die                               70035 -none- numeric
## dx_sev_die                               70035 -none- numeric
## diagnoses                                70035 -none- numeric
## deaths_of_diagnosed                      70035 -none- numeric
## fitted_cases                             70035 -none- numeric
## fitted_hospitalizations                  70035 -none- numeric
## fitted_deaths                            70035 -none- numeric
## fitted_cases_mvs                         70035 -none- numeric
## fitted_hospitalizations_mvs              70035 -none- numeric
## fitted_deaths_mvs                        70035 -none- numeric
## phi_cas                                   2001 -none- numeric
## phi_hosp                                  2001 -none- numeric
## infections_premiere                      70035 -none- numeric
## num_uninf                                70035 -none- numeric
## p_die_if_sym                              2001 -none- numeric
## susceptible_severe_prvl                  70035 -none- numeric
## effective_protection_inf_prvl            70035 -none- numeric
## effective_protection_inf_vax_prvl        70035 -none- numeric
## effective_protection_inf_vax_boost_prvl  70035 -none- numeric
## effective_protection_vax_prvl            70035 -none- numeric
## effective_protection_vax_boost_prvl      70035 -none- numeric
## fitted_wastewater_prvl                   70035 -none- numeric
## immunoexposed_cumulative                 70035 -none- numeric
## diag_cases                               70035 -none- numeric
## infections_cumulative                    70035 -none- numeric
## seropositive_prvl                        70035 -none- numeric
## infect_dist_rv                           10005 -none- numeric
## seropos_dist_rv                          10005 -none- numeric
## lp__                                      2001 -none- numeric
```
In this format, it's possible to view the time series of estimates within a single iteration. 

```r
# a matrix of new infection point estimates for each timepoint, iteration
symptomatic <- resultSampler[["extracted"]]$symptomatic
# view first 8 iterations, first 5 days
symptomatic[1:8, 1:5]
```

```
##           
## iterations        [,1]       [,2]      [,3]      [,4]      [,5]
##       [1,]   20.915638   83.52655  279.6354   852.035  1545.863
##       [2,]  465.373843 1219.99343 2224.2171  3279.559  3376.376
##       [3,]  315.124743  933.95830 2414.2607  5708.108  8962.015
##       [4,] 3578.576732 5496.18261 7867.6441 10448.528 10017.251
##       [5,]   11.749233  113.76340  563.1696  1722.781  2395.676
##       [6,]   59.485646  184.21509  520.2122  1407.977  2548.258
##       [7,]   30.221652  197.02279  871.2315  2549.490  4633.613
##       [8,]    9.974706  169.39580 1302.0273  4821.392  7332.001
##
```
This functionality is particularly useful for calculating an average with quantile-based bounds across multiple days of data. For example, we can calculate the average number of new infections over the first week of data. 

```r
# create a data frame with the final 7 days from the model 
symptomatic_df <- as.data.frame(symptomatic[,29:35]) 
# compute the row average 
symptomatic_df$avg <- rowSums(symptomatic_df)/7
# calculate the mean and 95% uncertainty bounds
quantile(symptomatic_df$avg, probs = c(0.025,  0.5, 0.975))
```

```
##       2.5%       50%     97.5% 
##   5742.445 13795.639 31927.407 
```
`extracted` is generally useful for cases where it's necessary to compute an average across multiple timepoints or when a user would like to represent uncertainty with non-quantile-based intervals (e.g. highest density intervals). 

### Summary
`summary` contains the point estimate and uncertainty bounds for every parameter in the model. The number in brackets indicates the index day of the estimate. `summary` also contains information about model fit, including the effective sample size and Rhat estimates. 

```r
head(resultSampler[["summary"]])
```

```
##                      mean    se_mean         sd       2.5%       25%      50%
## log_infections_0 4.002962 0.12482804 3.36767658 -2.5922594 1.7065459 4.093178
## serial_i         0.503513 0.00233125 0.07175278  0.3761696 0.4538342 0.497454
## spl_par_rt[1]    1.739605 0.02301083 0.64869189  0.4892591 1.3109598 1.732197
## spl_par_rt[2]    1.619298 0.01891424 0.51494689  0.6535037 1.2765966 1.609727
## spl_par_rt[3]    1.492020 0.01511776 0.40208886  0.7496523 1.2159287 1.480105
## spl_par_rt[4]    1.352475 0.01156291 0.30566562  0.7823028 1.1401596 1.345936
##                       75%      97.5%    n_eff      Rhat
## log_infections_0 6.289483 10.4427742 727.8409 1.0002831
## serial_i         0.550803  0.6577614 947.3268 1.0020477
## spl_par_rt[1]    2.173038  3.0171986 794.7166 0.9998344
## spl_par_rt[2]    1.964727  2.6432368 741.2200 0.9998162
## spl_par_rt[3]    1.757841  2.3007235 707.4070 1.0001236
## spl_par_rt[4]    1.556165  1.9627454 698.8092 1.0009470
##
```
While `summary` can be easily converted to a dataframe, we recommend using helper functions with covidestim. 
