---
title: "Running Covidcast with fake data"
author: "Marcus Russi"
date: "4/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fake data

```{r cars}
library(covidcast)
library(dplyr)
library(lubridate)
library(ggplot2)
library(magrittr)
```

```{r}
# Two keys: sim_repor[report_day, cases, hosp, deaths],
#           sim_true [report_day, cases, hosp, deaths]
n_days <- 50

# to account for bug in simulated_data
sim <- simulated_data(n_days=n_days) 

n_days_before <- min(sim$report$report_day) - 1

# Some reporting days have no data. In this case, we fill in these implicitly
# missing rows with zeroes for cases, hospitalizations, and deaths.
tidyr::complete(
  sim$report,
  report_day = min(sim$report$report_day):n_days,
  fill       = list(cases=0, hosp=0, deaths=0)
) -> report

# Just some arbitrary date
startdate <- now() - days(60)

reformat <- function(df, startdate, var)
  transmute(
    df,
    date        = startdate + days(report_day - 1),
    observation = !!rlang::sym(var)
  )

reported_cases  <- reformat(report, startdate, 'cases')
reported_hosp   <- reformat(report, startdate, 'hosp')
reported_deaths <- reformat(report, startdate, 'deaths')
```

This is the part where we load the data inputs into covidcast
```{r}
cfg <- covidcast(N_days=n_days-n_days_before+1, N_days_delay=n_days_before) +
  input_cases(reported_cases) +
  input_hospitalizations(reported_hosp) +
  input_deaths(reported_deaths)
```

```{r}
results <- run(cfg)
```


